name:         ghashboard
description:  "Builds dashboard pages with your Github Action badges"
author:       fileformat

branding:
  icon:   activity
  color:  blue

inputs:

  archived:
    description:  "include archived repos?"
    required:     false
  empty:
    description:  "include repos with no workflows (useful if you have external badges)"
    required:     false
  exclude:
    description:  "workflows to exclude"
    required:     false
  externals:
    description:  "external badges to include (usually only work with public repos)"
    required:     false
  footer:
    description:  "footer text"
    required:     false
  forks:
    description:  "include forked repos?"
    required:     false
  format:
    description:  "output format"
    required:     false
  header:
    description:  "header text"
    required:     false
  inactive:
    description:  "include inactive workflows?"
    required:     false
  include:
    description:  "workflows to include"
    required:     false
  log-level:
    description:  "log level [ debug | info | warn | error ]"
    required:     false
  output:
    description:  "output file to create (or `-` for stdout)"
    required:     false
  owners:
    description:  "list of owners (one of owner|repos is required)"
    required:     false
  private:
    description:  "include private repos? (one of public|private must be true)"
    required:     false
  public:
    description:  "include public repos? (one of public|private must be true)"
    required:     false
  repos:
    description:  "list of repos (one of owner|repos is required)"
    required:     false
  skip:
    description:  "do not include specific repos (use full owner/name)"
    required:     false
  title:
    description:  "title text"
    required:     false
  token:
    description:  "Github token (required for private repos and higher rate limits)"
    required:     false

runs:
  using: docker
  image: docker://ghcr.io/fileformat/ghashboard:latest
