name: build

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set some env vars for the build
        run: |
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "COMMIT=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "LASTMOD=${TIMESTAMP}" >> $GITHUB_ENV
          echo "BUILTBY=build.yaml" >> $GITHUB_ENV
          echo "IMAGE_NAME=fileformat/ghashboard" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          build-args: |
            COMMIT=${{ env.COMMIT }}
            LASTMOD=${{ env.LASTMOD }}
            VERSION=custombuild
            BUILTBY=${{ env.BUILTBY }}
